/**:
  ros__parameters:
    voxel_leaf_size: 0.25

    roi:
      x_min: 0.0
      x_max: 40.0
      y_min: -6.0
      y_max: 6.0
      z_min: -2.0
      z_max: 2.5

    cluster:
      tolerance: 0.6
      min_size: 5
      max_size: 2000